In [1]:
import numpy as np
import pandas as pd
import tushare as ts
from pandas import DataFrame, Series

In [2]:
zixuan_codes = pd.DataFrame([['上指', 'sh'], ['深指', 'sz'], ['创指', 'cyb'], ['创业板B', '150153'], ['互联网B', '150195'], ['煤炭B', '150290'], ['钢铁B', '150288'], ['证券B', '150172'], ['房地产B', '150118'], ['国防B', '150206'], ['克明面业', '002661'], ['第一创业', '002797'], ['万科A', '000002'], ['恒生电子', '600570'], ['天顺股份', '002800'], ['深物业A', '000011'], ['龙洲股份', '002682'], ['浙江世宝', '002703']])
def get_realtime_info():
    rti = ts.get_realtime_quotes(zixuan_codes[1])
    rti['percent'] = [100.0 * (float(rti['price'][i]) - float(rti['pre_close'][i]))/float(rti['pre_close'][i]) for i in range(len(rti.index))]
    rti['amount'] = [float(rti['amount'][i]) / 100000000.0 for i in range(len(rti.index))]
    return rti[['name','code','price','percent','high','low','amount','time']]

In [3]:
def code2str(cd):
    if cd < 10:
        scd = '00000%d' % cd
        return scd
    elif cd < 100:
        scd = '0000%d' % cd
        return scd
    elif cd < 1000:
        scd = '000%d' % cd
        return scd
    elif cd < 10000:
        scd = '00%d' % cd
        return scd
    elif cd < 100000:
        scd = '0%d' % cd
        return scd
    else:
        scd = str(cd)
        return scd

In [101]:
get_realtime_info()

,name,code,price,percent,high,low,amount,time
0,上证指数,000001,3206.9858,-0.105446,3214.2920,3195.0353,2670.038709,15:01:03
1,深证成指,399001,10958.104,0.463707,10958.104,10877.396,3636.947670,15:01:03
2,创业板指,399006,2179.300,0.814827,2179.300,2152.375,279.429095,15:01:03
3,创业板B,150153,0.968,3.198294,0.980,0.920,6.992872,15:01:03
4,互联网B,150195,0.486,3.846154,0.492,0.461,3.098656,15:01:03
5,煤炭B级,150290,0.669,-3.879310,0.720,0.656,1.568620,15:01:03
6,钢铁B,150288,0.578,-1.867572,0.601,0.567,0.852745,15:01:03
7,证券B,150172,1.374,-0.794224,1.394,1.358,3.777902,15:01:03
8,房地产B,150118,0.515,4.674797,0.529,0.488,0.821794,15:01:03
9,国防B,150206,0.497,-0.200803,0.500,0.486,2.848426,15:01:03
10,克明面业,002661,18.230,0.219901,18.300,18.100,0.364885,15:01:03
11,第一创业,002797,43.360,-1.364877,44.440,43.000,14.391270,15:01:03
12,万 科Ａ,000002,26.940,4.824903,27.800,25.460,39.658937,15:01:03
13,恒生电子,600570,59.890,0.385518,60.190,58.850,9.585064,15:00:00
14,天顺股份,002800,82.090,-1.084468,83.880,81.600,1.281096,15:01:03
15,深物业A,000011,18.720,0.429185,18.950,18.300,1.954832,15:01:03
16,龙洲股份,002682,14.980,0.604433,14.990,14.530,0.933981,15:01:03
17,浙江世宝,002703,48.010,0.840160,48.690,47.000,3.731571,15:01:03

In [39]:
allstock = pd.read_csv('AllStock.csv')

In [6]:
zfse = Series()
for i in range(len(zixuan_codes.index)):
    data = ts.get_k_data(code=zixuan_codes[1][i], start='2016-10-01', end='2016-11-13')
    if len(data.index) > 10:
        zf = Series([(float(data['high'][j]) - float(data['low'][j])) / float(data['close'][j-1]) * 100 if j > 0 else np.nan for j in range(len(data.index))])
        zfm = zf.mean()
        zfse[zixuan_codes[1][i]] = zf.mean()
zfse

sh        0.831256
sz        0.887672
cyb       1.077302
150153    2.167240
150195    2.633333
150290    5.824464
150288    2.864506
150172    2.919846
150118    2.883831
150206    3.212108
002661    2.436581
002797    4.416816
000002    3.563151
600570    2.498148
002800    4.404989
000011    4.442714
002682    3.256631
002703    6.710803
dtype: float64

In [7]:
allstock['code'][0]

603977

In [25]:
datas = ts.get_k_data('002703',start='2016-08-01', end='2016-11-13')
datas['zf'] = [(100.0 * (float(datas['high'][j]) - float(datas['low'][j])) / float(datas['close'][j-1])) if j > 0 else np.nan for j in range(len(datas.index))]
datas

          date    open   close    high     low      volume    code         zf
0   2016-08-01  33.000  30.560  33.350  30.560  176073.000  002703        NaN
1   2016-08-02  29.680  29.600  30.360  28.640  151935.000  002703   5.628272
2   2016-08-03  29.300  29.880  30.430  29.150  129483.000  002703   4.324324
3   2016-08-04  30.010  29.900  30.250  28.900  112978.000  002703   4.518072
4   2016-08-05  29.700  30.870  31.450  29.530  149449.000  002703   6.421405
5   2016-08-08  30.310  30.300  30.570  29.790   93614.000  002703   2.526725
6   2016-08-09  30.420  30.770  31.300  29.900  122178.000  002703   4.620462
7   2016-08-10  30.760  33.020  33.850  30.500  224225.000  002703  10.887228
8   2016-08-11  32.860  36.320  36.320  32.550  218985.000  002703  11.417323
9   2016-08-12  37.000  39.580  39.900  35.850  435298.000  002703  11.150881
10  2016-08-15  38.330  43.540  43.540  37.810  375216.000  002703  14.477009
11  2016-08-16  43.540  47.890  47.890  42.610  394717.000  002703  12.126780
12  2016-08-17  45.200  43.890  47.660  43.500  381904.000  002703   8.686573
13  2016-08-18  43.560  44.600  45.800  42.800  317601.000  002703   6.835270
14  2016-08-19  43.560  42.430  44.440  42.030  237828.000  002703   5.403587
15  2016-08-22  42.430  42.010  43.400  41.900  169091.000  002703   3.535235
16  2016-08-23  42.010  42.550  42.890  40.880  190545.000  002703   4.784575
17  2016-08-24  42.790  41.160  42.800  40.690  161483.000  002703   4.958872
18  2016-08-25  41.400  41.580  42.770  41.010  210707.000  002703   4.275996
19  2016-08-26  40.750  40.020  41.200  39.780  173347.000  002703   3.415103
20  2016-08-29  40.090  39.500  40.200  38.980  109404.000  002703   3.048476
21  2016-08-30  39.810  43.170  43.400  39.180  314591.000  002703  10.683544
22  2016-08-31  41.990  44.600  46.770  41.900  361667.000  002703  11.280982
23  2016-09-01  44.140  41.050  44.500  41.000  249944.000  002703   7.847534
24  2016-09-02  40.000  40.200  41.590  39.290  153541.000  002703   5.602923
25  2016-09-05  40.140  40.960  41.490  40.140  125679.000  002703   3.358209
26  2016-09-06  40.460  40.150  40.680  39.060  130596.000  002703   3.955078
27  2016-09-07  40.170  40.950  41.780  39.620  166782.000  002703   5.379826
28  2016-09-08  40.680  40.020  40.680  39.690   93694.000  002703   2.417582
29  2016-09-09  40.020  39.160  40.720  39.080   83836.000  002703   4.097951
30  2016-09-12  37.600  36.810  38.490  36.510  106876.000  002703   5.056180
31  2016-09-13  37.500  37.160  38.250  36.910   93916.000  002703   3.640315
32  2016-09-14  36.880  37.290  37.900  36.140   89296.000  002703   4.736276
33  2016-09-19  37.250  37.420  37.860  37.100   60666.000  002703   2.038080
34  2016-09-20  37.600  41.160  41.160  37.440  210078.000  002703   9.941208
35  2016-09-21  41.600  40.600  42.500  40.310  211168.000  002703   5.320700
36  2016-09-22  41.250  41.270  42.370  40.530  191876.000  002703   4.532020
37  2016-09-23  40.510  41.560  43.200  40.510  186957.000  002703   6.518052
38  2016-09-26  40.890  42.580  44.460  40.570  271954.000  002703   9.359962
39  2016-09-27  42.610  42.640  43.330  40.460  189620.000  002703   6.740254
40  2016-09-28  42.180  43.690  44.700  42.110  242530.000  002703   6.074109
41  2016-09-29  43.390  41.830  43.950  41.550  178852.000  002703   5.493248
42  2016-09-30  41.660  41.270  42.470  40.620  133732.000  002703   4.422663
43  2016-10-10  41.900  42.370  42.670  40.720  131535.000  002703   4.724982
44  2016-10-24  44.300  46.610  46.610  43.480  259546.000  002703   7.387302
45  2016-10-25  47.000  45.290  49.490  45.220  338277.000  002703   9.161124
46  2016-10-26  44.140  43.840  45.280  43.090  187876.000  002703   4.835505
47  2016-10-27  43.730  46.600  46.860  43.210  182364.000  002703   8.325730
48  2016-10-28  46.230  47.950  48.970  45.760  300722.000  002703   6.888412
49  2016-10-31  47.010  46.630  48.370  45.000  173572.000  002703   7.028154
50  2016-11-01  46.160  47.150  48.200  46.160  162302.000  002703   4.374866
51  2016-11-02  46.800  51.020  51.870  46.180  374709.000  002703  12.067869
52  2016-11-03  50.100  50.150  52.380  49.500  326448.000  002703   5.644845
53  2016-11-04  49.500  50.890  53.030  49.500  258634.000  002703   7.038883
54  2016-11-07  50.000  51.410  51.410  48.180  171352.000  002703   6.347023
55  2016-11-08  51.800  50.020  52.860  50.000  161028.000  002703   5.563120
56  2016-11-09  49.130  48.150  49.970  46.860  152493.000  002703   6.217513
57  2016-11-10  49.250  50.560  50.650  48.140  145415.000  002703   5.212876
58  2016-11-11  51.240  49.900  51.970  49.660  175428.000  002703   4.568829

In [26]:
datas.mean()

zf    6.326309
dtype: float64

In [24]:
datas_zf = Series([(100.0 * (float(datas['high'][j]) - float(datas['low'][j])) / float(datas['close'][j-1])) if j > 0 else np.nan for j in range(len(datas.index))])
datas_zf

0           NaN
1      7.387302
2      9.161124
3      4.835505
4      8.325730
5      6.888412
6      7.028154
7      4.374866
8     12.067869
9      5.644845
10     7.038883
11     6.347023
12     5.563120
13     6.217513
14     5.212876
15     4.568829
dtype: float64

In [10]:
datas_zf.mean()

6.7108034586196288

In [208]:
# zf>=4 and highper>=1 and lowper<=-1
def getGoodDays(stockcode, startdate, enddate):
    data = ts.get_k_data(stockcode, start=startdate, end=enddate)
    data['zf'] = [(float(data['high'][i]) - float(data['low'][i])) / float(data['close'][i-1]) * 100 if i > 0 else np.nan for i in range(len(data.index))]
    data['high_per'] = [float(data['high'][i]) / float(data['close'][i-1]) * 100 - 100 if i > 0 else np.nan for i in range(len(data.index))]
    data['low_per'] = [float(data['low'][i]) / float(data['close'][i-1]) * 100 - 100 if i > 0 else np.nan for i in range(len(data.index))]
    data['good_t_day'] = [True if data['zf'][i] >= 4 and data['high_per'][i] >= 1 and data['low_per'][i] <= -1 else False for i in range(len(data.index))]
    data['buy_sell_good'] = False
    data['sell_buy_good'] = False
    for i in range(1, len(data.index)):
        if data['good_t_day'][i]:
            ticks = ts.get_tick_data(code=stockcode, date=data['date'][i])
            if len(ticks.index) <= 0:
                continue
            lasthigh = -1
            lastlow = -1
            firsthigh = -1
            firstlow = -1
            for j in range(len(ticks.index)):
                if (float(ticks['price'][j]) / float(data['close'][i-1]) * 100 - 100) >= 1 and lasthigh == -1:
                    lasthigh = j
                if (float(ticks['price'][j]) / float(data['close'][i-1]) * 100 - 100) <= -1 and lastlow == -1:
                    lastlow = j
                if lasthigh >= 0 and lastlow >=0:
                    break
            tlen = len(ticks.index) - 1
            while tlen >= 0:
                if (float(ticks['price'][j]) / float(data['close'][i-1]) * 100 - 100) >= 1 and firsthigh == -1:
                    firsthigh = tlen
                if (float(ticks['price'][j]) / float(data['close'][i-1]) * 100 - 100) <= -1 and firstlow == -1:
                    firstlow = tlen
                if firsthigh >= 0 and firstlow >=0:
                    break
                tlen -= 1
            data['sell_buy_good'][i] = firsthigh < lastlow
            data['buy_sell_good'][i] = firstlow < lasthigh
    return data

In [206]:
sbdata = getGoodDays(stockcode='002703', startdate='2016-08-01', enddate='2016-11-15')
sbdata

e:\tools(x86)\python343\lib\site-packages\ipykernel\__main__.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
e:\tools(x86)\python343\lib\site-packages\ipykernel\__main__.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,date,open,close,high,low,volume,code,zf,high_per,low_per,good_t_day,buy_sell_good,sell_buy_good
0,2016-08-01,33.000,30.560,33.350,30.560,176073.000,002703,NaN,NaN,NaN,False,False,False
1,2016-08-02,29.680,29.600,30.360,28.640,151935.000,002703,5.628272,-0.654450,-6.282723,False,False,False
2,2016-08-03,29.300,29.880,30.430,29.150,129483.000,002703,4.324324,2.804054,-1.520270,True,False,True
3,2016-08-04,30.010,29.900,30.250,28.900,112978.000,002703,4.518072,1.238286,-3.279786,True,False,True
4,2016-08-05,29.700,30.870,31.450,29.530,149449.000,002703,6.421405,5.183946,-1.237458,True,True,False
5,2016-08-08,30.310,30.300,30.570,29.790,93614.000,002703,2.526725,-0.971817,-3.498542,False,False,False
6,2016-08-09,30.420,30.770,31.300,29.900,122178.000,002703,4.620462,3.300330,-1.320132,True,False,True
7,2016-08-10,30.760,33.020,33.850,30.500,224225.000,002703,10.887228,10.009750,-0.877478,False,False,False
8,2016-08-11,32.860,36.320,36.320,32.550,218985.000,002703,11.417323,9.993943,-1.423380,True,False,True
9,2016-08-12,37.000,39.580,39.900,35.850,435298.000,002703,11.150881,9.856828,-1.294053,True,False,True
10,2016-08-15,38.330,43.540,43.540,37.810,375216.000,002703,14.477009,10.005053,-4.471956,True,False,True
11,2016-08-16,43.540,47.890,47.890,42.610,394717.000,002703,12.126780,9.990813,-2.135967,True,False,True
12,2016-08-17,45.200,43.890,47.660,43.500,381904.000,002703,8.686573,-0.480267,-9.166841,False,False,False
13,2016-08-18,43.560,44.600,45.800,42.800,317601.000,002703,6.835270,4.351789,-2.483481,True,False,True
14,2016-08-19,43.560,42.430,44.440,42.030,237828.000,002703,5.403587,-0.358744,-5.762332,False,False,False
15,2016-08-22,42.430,42.010,43.400,41.900,169091.000,002703,3.535235,2.286118,-1.249116,False,False,False
16,2016-08-23,42.010,42.550,42.890,40.880,190545.000,002703,4.784575,2.094739,-2.689836,True,False,True
17,2016-08-24,42.790,41.160,42.800,40.690,161483.000,002703,4.958872,0.587544,-4.371328,False,False,False
18,2016-08-25,41.400,41.580,42.770,41.010,210707.000,002703,4.275996,3.911565,-0.364431,False,False,False
19,2016-08-26,40.750,40.020,41.200,39.780,173347.000,002703,3.415103,-0.913901,-4.329004,False,False,False
20,2016-08-29,40.090,39.500,40.200,38.980,109404.000,002703,3.048476,0.449775,-2.598701,False,False,False
21,2016-08-30,39.810,43.170,43.400,39.180,314591.000,002703,10.683544,9.873418,-0.810127,False,False,False
22,2016-08-31,41.990,44.600,46.770,41.900,361667.000,002703,11.280982,8.339124,-2.941858,True,False,True
23,2016-09-01,44.140,41.050,44.500,41.000,249944.000,002703,7.847534,-0.224215,-8.071749,False,False,False
24,2016-09-02,40.000,40.200,41.590,39.290,153541.000,002703,5.602923,1.315469,-4.287454,True,True,False
25,2016-09-05,40.140,40.960,41.490,40.140,125679.000,002703,3.358209,3.208955,-0.149254,False,False,False
26,2016-09-06,40.460,40.150,40.680,39.060,130596.000,002703,3.955078,-0.683594,-4.638672,False,False,False
27,2016-09-07,40.170,40.950,41.780,39.620,166782.000,002703,5.379826,4.059776,-1.320050,True,False,True
28,2016-09-08,40.680,40.020,40.680,39.690,93694.000,002703,2.417582,-0.659341,-3.076923,False,False,False
29,2016-09-09,40.020,39.160,40.720,39.080,83836.000,002703,4.097951,1.749125,-2.348826,True,True,False
30,2016-09-12,37.600,36.810,38.490,36.510,106876.000,002703,5.056180,-1.710930,-6.767109,False,False,False
31,2016-09-13,37.500,37.160,38.250,36.910,93916.000,002703,3.640315,3.911980,0.271665,False,False,False
32,2016-09-14,36.880,37.290,37.900,36.140,89296.000,002703,4.736276,1.991389,-2.744887,True,False,True
33,2016-09-19,37.250,37.420,37.860,37.100,60666.000,002703,2.038080,1.528560,-0.509520,False,False,False
34,2016-09-20,37.600,41.160,41.160,37.440,210078.000,002703,9.941208,9.994655,0.053447,False,False,False
35,2016-09-21,41.600,40.600,42.500,40.310,211168.000,002703,5.320700,3.255588,-2.065112,True,True,False
36,2016-09-22,41.250,41.270,42.370,40.530,191876.000,002703,4.532020,4.359606,-0.172414,False,False,False
37,2016-09-23,40.510,41.560,43.200,40.510,186957.000,002703,6.518052,4.676520,-1.841531,True,False,True
38,2016-09-26,40.890,42.580,44.460,40.570,271954.000,002703,9.359962,6.977863,-2.382098,True,False,True
39,2016-09-27,42.610,42.640,43.330,40.460,189620.000,002703,6.740254,1.761390,-4.978863,True,False,True
40,2016-09-28,42.180,43.690,44.700,42.110,242530.000,002703,6.074109,4.831144,-1.242964,True,False,True
41,2016-09-29,43.390,41.830,43.950,41.550,178852.000,002703,5.493248,0.595102,-4.898146,False,False,False
42,2016-09-30,41.660,41.270,42.470,40.620,133732.000,002703,4.422663,1.530002,-2.892661,True,True,False
43,2016-10-10,41.900,42.370,42.670,40.720,131535.000,002703,4.724982,3.392295,-1.332687,True,False,True
44,2016-10-24,44.300,46.610,46.610,43.480,259546.000,002703,7.387302,10.007080,2.619778,False,False,False
45,2016-10-25,47.000,45.290,49.490,45.220,338277.000,002703,9.161124,6.178932,-2.982193,True,True,False
46,2016-10-26,44.140,43.840,45.280,43.090,187876.000,002703,4.835505,-0.022080,-4.857584,False,False,False
47,2016-10-27,43.730,46.600,46.860,43.210,182364.000,002703,8.325730,6.888686,-1.437044,True,False,True
48,2016-10-28,46.230,47.950,48.970,45.760,300722.000,002703,6.888412,5.085837,-1.802575,True,False,True
49,2016-10-31,47.010,46.630,48.370,45.000,173572.000,002703,7.028154,0.875912,-6.152242,False,False,False
50,2016-11-01,46.160,47.150,48.200,46.160,162302.000,002703,4.374866,3.366931,-1.007935,True,False,True
51,2016-11-02,46.800,51.020,51.870,46.180,374709.000,002703,12.067869,10.010604,-2.057264,True,False,True
52,2016-11-03,50.100,50.150,52.380,49.500,326448.000,002703,5.644845,2.665621,-2.979224,True,True,False
53,2016-11-04,49.500,50.890,53.030,49.500,258634.000,002703,7.038883,5.742772,-1.296112,True,False,True
54,2016-11-07,50.000,51.410,51.410,48.180,171352.000,002703,6.347023,1.021812,-5.325211,True,False,True
55,2016-11-08,51.800,50.020,52.860,50.000,161028.000,002703,5.563120,2.820463,-2.742657,True,True,False
56,2016-11-09,49.130,48.150,49.970,46.860,152493.000,002703,6.217513,-0.099960,-6.317473,False,False,False
57,2016-11-10,49.250,50.560,50.650,48.140,145415.000,002703,5.212876,5.192108,-0.020768,False,False,False
58,2016-11-11,51.240,49.900,51.970,49.660,175428.000,002703,4.568829,2.788766,-1.780063,True,True,False
59,2016-11-14,48.690,47.610,49.430,47.600,129749.000,002703,3.667335,-0.941884,-4.609218,False,False,False

In [207]:
print(sbdata['good_t_day'].sum(), sbdata['buy_sell_good'].sum(), sbdata['sell_buy_good'].sum())

32 9 23

In [128]:
ts.get_k_data(code='002703', ktype='D', start='2016-08-03', end='2016-08-04')

         date    open   close    high     low      volume    code
0  2016-08-03  29.300  29.880  30.430  29.150  129483.000  002703
1  2016-08-04  30.010  29.900  30.250  28.900  112978.000  002703

In [188]:
print(sbtick.ix[[1895,2690,731,2196]])

          time  price change  volume  amount type
1895  10:30:39  18.85   0.04     100  188500   买盘
2690  09:30:06  18.30  -0.21     504  922320   卖盘
731   13:40:57  18.83     --      19   35777   卖盘
2196  10:06:33  18.45  -0.01       5    9225   卖盘